//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkDigTest.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkDigTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   # 見出し1
        ///## 見出し2
        ///### 見出し3
        ///#### 見出し4
        ///##### 見出し5
        ///###### 見出し6
        ///
        ///- リスト1
        ///    - ネスト リスト1_1
        ///        - ネスト リスト1_1_1
        ///        - ネスト リスト1_1_2
        ///    - ネスト リスト1_2
        ///- リスト2
        ///
        ///1. 番号付きリスト1
        ///    1. 番号付きリスト1_1
        ///    1. 番号付きリスト1_2
        ///1. 番号付きリスト2
        ///
        ///## 引用
        ///&gt; お世話になります。xxxです。
        ///&gt;
        ///&gt; ご連絡いただいた、バグの件ですが、仕様です。
        ///&gt; &gt; お世話になります。 yyyです。
        ///&gt; &gt;
        ///&gt; &gt; あの新機能バグってるっすね
        ///
        ///## code記法
        ///
        ///```csharp
        ///public class Person
        ///{
        ///   public string Name {get;set;}
        ///}
        ///```
        ///`Age`は`18` です。
        ///
        ///## 強調
        ///
        ///normal *italic* normal
        ///
        ///normal ***bold*** normal
        ///
        ///## Ta [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MarkDownText {
            get {
                return ResourceManager.GetString("MarkDownText", resourceCulture);
            }
        }
    }
}
